spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bike_share?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 124356tbw
    initial-size: 10
    max-active: 20
    min-idle: 8
  application:
    name: bike-service #此springboot模块提供单车增删改查微服务
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

# 静态资源配置
resources:
  static-locations: classpath:static/

# thymeleaf模板引擎配置
thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  mode: HTML5
  encoding: UTF-8
  content-type: text/html
  cache: false

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.bike.bean

logging:
  level:
    com:
      example:
        bike:
          mapper: debug

server:
  port: 8503 # 单车微服务注册的端口
