server:
  port: 8500

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bike_share?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    web-application-type: reactive
  application:
    name: nacos-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: login-service-route
          uri: http://localhost:8502
          predicates:
            - Path=/login-service/**
          filters:
            - StripPrefix=1

        - id: service-consumer-route
          uri: http://localhost:8501
          predicates:
            - Path=/service-consumer/**
          filters:
            - StripPrefix=1

        - id: bike-service-route
          uri: http://localhost:8503
          predicates:
            - Path=/bike-service/**
          filters:
            - StripPrefix=1

        - id: user-service-route
          uri: http://localhost:8504
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1

        - id: lend-service-route
          uri: http://localhost:8505
          predicates:
            - Path=/lend-service/**
          filters:
            - StripPrefix=1

        - id: repair-service-route
          uri: http://localhost:8506
          predicates:
            - Path=/repair-service/**
          filters:
            - StripPrefix=1



